upload new recipes
sporeprotocol/spore-docs pull request #38
Opened 2023-11-06 02:41 UTC by anipenguin

- Melt Spore
- Transfer Spore/Cluster
- Disable Zero-fee Transfer
- Configure Zero-fee Transfer (post creation)
- added "Configure Zero-fee Transfer" under extra of "Create Spore"

2023-11-07 20:12 UTC, ShookLyngs requested changes

2023-11-07 20:14 UTC, anipenguin commented on docs/recipes/create-private-cluster.mdx
> +- `fromInfos` - The transaction's sponsor, specifies where to collect capacity from.
can you have multiple addresses to sponsor the transaction?

2023-11-07 20:18 UTC, ShookLyngs commented on docs/recipes/create-private-cluster.mdx
> +- `fromInfos` - The transaction's sponsor, specifies where to collect capacity from.
Yes, `fromInfos` accepts a list of `FromInfo`, you can pass multiple fromInfos like this:

```
fromInfos: [Charlie, Alice],
```

2023-11-07 20:18 UTC, anipenguin commented on docs/recipes/modify-0-fee-transfer.md
> +Every spore, when created, is fueled with 1 CKBytes as “gas” that covers about `100,000` future transactions. This default setting, referred as the  [Zero-fee Transfer](/basics/spore-101#do-i-need-to
makes sense, i'm drafting a post about the concept of "capacity margin" separately under Get Started

2023-11-07 20:20 UTC, anipenguin commented on docs/recipes/create-private-cluster.mdx
> +- `fromInfos` - The transaction's sponsor, specifies where to collect capacity from.
okay, was not aware of this, how do they split the transaction fee in practice?

2023-11-07 20:27 UTC, ShookLyngs commented on docs/recipes/create-private-cluster.mdx
> +- `fromInfos` - The transaction's sponsor, specifies where to collect capacity from.
I believe the logic behind this is as follows: 
- `Charlie` pays as much as he can
- If `Charlie` is unable to pay the full fee, `Alice` covers the remaining amount.

2023-11-07 21:09 UTC, anipenguin reviewed
[OWNER_ADDRESS] -> [SPONSOR_ADDRESS] to avoid confusion

2023-11-07 21:09 UTC, anipenguin commented on docs/recipes/disable-0-fee-transfer.md
> +- `fromInfos` - The transaction's sponsor, specifies where to collect capacity from.
```suggestion
- `fromInfos` - The transaction's sponsors, specifies where to collect capacity from.
```

2023-11-07 21:09 UTC, anipenguin commented on docs/recipes/disable-0-fee-transfer.md
> +  fromInfos: [OWNER_ADDRESS],
```suggestion
  fromInfos: [SPONSOR_ADDRESS],
```

2023-11-07 21:09 UTC, anipenguin commented on docs/recipes/disable-0-fee-transfer.md
> +  fromInfos: [OWNER_ADDRESS],
```suggestion
  fromInfos: [SPONSOR_ADDRESS],
```

2023-11-07 21:09 UTC, anipenguin commented on docs/recipes/disable-0-fee-transfer.md
> +- `fromInfos` - The transaction's sponsor, specifies where to collect capacity from.
```suggestion
- `fromInfos` - The transaction's sponsors, specifies where to collect capacity from.
```

2023-11-07 21:09 UTC, anipenguin commented on docs/recipes/melt-spore.mdx
> +- `fromInfos` - The transaction's sponsor, specifies where to collect capacity from.
```suggestion
- `fromInfos` - The transaction's sponsors, specifies where to collect capacity from.
```

2023-11-07 21:09 UTC, anipenguin commented on docs/recipes/melt-spore.mdx
> +  fromInfos: [OWNER_ADDRESS],
```suggestion
  fromInfos: [SPONSOR_ADDRESS],
```

2023-11-07 21:09 UTC, anipenguin commented on docs/recipes/modify-0-fee-transfer.md
> +  fromInfos: [OWNER_ADDRESS],
```suggestion
  fromInfos: [SPONSOR_ADDRESS],
```

2023-11-07 21:09 UTC, anipenguin commented on docs/recipes/modify-0-fee-transfer.md
> +- `fromInfos` - The transaction's sponsor, specifies where to collect capacity from.
```suggestion
- `fromInfos` - The transaction's sponsors, specifies where to collect capacity from.
```

2023-11-07 21:16 UTC, anipenguin commented on docs/recipes/create-spore.mdx
> +The Zero-fee Transfer feature is enabled by reserving a small amount of CKBytes as fee for future transactions. When creating a spore, the default is to allocate 1 CKB (100,000,000 shannons) as capac
updated to "The Zero-fee Transfer feature enables recipients to transact spores without additional costs by reserving a tiny amount of CKBytes as fee for future transactions. When creating a spore, the default is to allocate 1 CKB (100,000,000 shannons) as capacity margin to cover about 100,000 future transaction."

2023-11-07 21:17 UTC, anipenguin reviewed
make modifications accordingly

2023-11-08 08:07 UTC, anipenguin reviewed
made changes accordingly

2023-11-08 18:06 UTC, ShookLyngs approved these changes

2023-11-08 22:25 UTC, merged