update technical design and terms in glossary
sporeprotocol/spore-docs pull request #48
Opened 2023-12-20 04:53 UTC by anipenguin

added more explanation of type args under "technical design"
updated def'n of "type id" and "tokenomics"

2023-12-20 16:21 UTC, code-monad commented on docs/glossary/terms.md
> -## TypeID
should be `TypeID` I think

2023-12-20 16:25 UTC, ShookLyngs requested changes

2023-12-20 16:25 UTC, ShookLyngs commented on docs/basics/technical-design/index.mdx
>  ```css
```suggestion
```yaml
```
Format in css is a bit far from the reality, maybe yaml? @code-monad

2023-12-22 06:34 UTC, ShookLyngs approved these changes

2023-12-22 06:35 UTC, merged